import re
from pydantic_settings import BaseSettings
from pathlib import Path


class Settings(BaseSettings):
    # Paths
    BUILDER_PATH: Path = Path(__file__).resolve().parent
    CORE_PATH: Path = BUILDER_PATH.parent
    MODULES_PATH: Path = CORE_PATH / "modules"
    SHARED_PATH: Path = MODULES_PATH / "_shared"
    RASA_PATH: Path = CORE_PATH / "rasa"
    DATA_PATH: Path = RASA_PATH / "data"
    SCHEMA_FILE: Path = BUILDER_PATH / "schemas" / "manifest.schema.json"

    GEN_HEADER: str = "# GENERATED by CommandEngine builder, version 1.0\n"
    RASA_VERSION: str = "3.1"
    ENTITY_RE: re.Pattern = re.compile(r"\]\(([a-z0-9_]+)\)")


settings = Settings()